import { SessionProvider } from "next-auth/react";
import { Toaster } from "~/components/ui/sonner";
import { Footer } from "~/components/footer";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { auth } from "~/auth";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "whriviera",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Toaster />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
